/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventaris;

/**
 *
 * @author kimen
 */
public class GUI_Kenyamanan extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Kenyamanan
     */
    public GUI_Kenyamanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Status_Kelas = new javax.swing.JButton();
        Menu_Data = new javax.swing.JButton();
        Menu_Kenyamanan = new javax.swing.JButton();
        Menu_Lingkungan = new javax.swing.JButton();
        Menu_Keamanan = new javax.swing.JButton();
        Menu_Kebersihan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bising = new javax.swing.JCheckBox();
        T_Bising = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Bau = new javax.swing.JCheckBox();
        T_Bau = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Bocor = new javax.swing.JCheckBox();
        T_Bocor = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Rusak = new javax.swing.JCheckBox();
        T_Rusak = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Aus = new javax.swing.JCheckBox();
        T_Aus = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Status_Kelas.setText("Inventaris");
        jPanel1.add(Status_Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        Menu_Data.setText("Data Pengguna");
        Menu_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_DataActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        Menu_Kenyamanan.setText("Kenyamanan");
        jPanel1.add(Menu_Kenyamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 40));

        Menu_Lingkungan.setText("Lingkungan");
        Menu_Lingkungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LingkunganActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Lingkungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        Menu_Keamanan.setText("Keamanan");
        Menu_Keamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KeamananActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Keamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        Menu_Kebersihan.setText("Kebersihan");
        Menu_Kebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KebersihanActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Kebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -50, -1, 40));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 430));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATA KENYAMANAN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 430, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("1. Kebisingan Ruangan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        Bising.setText("Bising");
        Bising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BisingActionPerformed(evt);
            }
        });
        jPanel2.add(Bising, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        T_Bising.setText("Tidak Bising");
        T_Bising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_BisingActionPerformed(evt);
            }
        });
        jPanel2.add(T_Bising, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("2. Aroma Ruangan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        Bau.setText("Bau");
        Bau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BauActionPerformed(evt);
            }
        });
        jPanel2.add(Bau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        T_Bau.setText("Tidak Bau");
        T_Bau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_BauActionPerformed(evt);
            }
        });
        jPanel2.add(T_Bau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setText("3. Kebocoran Di dalam Ruangan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 20));

        Bocor.setText("Bocor");
        Bocor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BocorActionPerformed(evt);
            }
        });
        jPanel2.add(Bocor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        T_Bocor.setText("Tidak Bocor");
        T_Bocor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_BocorActionPerformed(evt);
            }
        });
        jPanel2.add(T_Bocor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setText("4. Kerusakan Ruangan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 20));

        Rusak.setText("Rusak");
        Rusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RusakActionPerformed(evt);
            }
        });
        jPanel2.add(Rusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        T_Rusak.setText("Tidak Rusak");
        T_Rusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_RusakActionPerformed(evt);
            }
        });
        jPanel2.add(T_Rusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setText("5. Keausan Ruangan");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 20));

        Aus.setText("Aus");
        Aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AusActionPerformed(evt);
            }
        });
        jPanel2.add(Aus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        T_Aus.setText("Tidak Aus");
        T_Aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_AusActionPerformed(evt);
            }
        });
        jPanel2.add(T_Aus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_DataActionPerformed
        GUI_Data_Kelas gdk = new GUI_Data_Kelas();
        gdk.Data_Kelas();
    }//GEN-LAST:event_Menu_DataActionPerformed

    private void Menu_LingkunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LingkunganActionPerformed
        GUI_Lingkungan call_lingkung = new GUI_Lingkungan();
        call_lingkung.Lingkungan_GUI();
    }//GEN-LAST:event_Menu_LingkunganActionPerformed

    private void Menu_KeamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KeamananActionPerformed
        GUI_Keamanan aman = new GUI_Keamanan();
        aman.Keamanan_GUI();
    }//GEN-LAST:event_Menu_KeamananActionPerformed

    private void Menu_KebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KebersihanActionPerformed
        GUI_Kebersihan bersih = new GUI_Kebersihan();
        bersih.Kebersihan_GUI();
    }//GEN-LAST:event_Menu_KebersihanActionPerformed
Analisis nyaman = new Analisis();
    private void BisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BisingActionPerformed
        if(Bising.isSelected()){
            T_Bising.setSelected(false);
            nyaman.setKebisingan("bising");
        }
    }//GEN-LAST:event_BisingActionPerformed

    private void T_BisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_BisingActionPerformed
        if(T_Bising.isSelected()){
            Bising.setSelected(false);
            nyaman.setKebisingan("tidak_bising");
        }
    }//GEN-LAST:event_T_BisingActionPerformed

    private void BauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BauActionPerformed
        if(Bau.isSelected()){
            T_Bau.setSelected(false);
            nyaman.setBau("bau");
        }
    }//GEN-LAST:event_BauActionPerformed

    private void T_BauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_BauActionPerformed
        if(T_Bau.isSelected()){
            Bau.setSelected(false);
            nyaman.setBau("tidak_bau");
        }
    }//GEN-LAST:event_T_BauActionPerformed

    private void BocorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BocorActionPerformed
        if(Bocor.isSelected()){
            T_Bocor.setSelected(false);
            nyaman.setKebocoran("bocor");
        }
    }//GEN-LAST:event_BocorActionPerformed

    private void T_BocorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_BocorActionPerformed
        if(T_Bocor.isSelected()){
            Bocor.setSelected(false);
            nyaman.setKebocoran("tidak_bocor");
        }
    }//GEN-LAST:event_T_BocorActionPerformed

    private void RusakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RusakActionPerformed
        if(Rusak.isSelected()){
            T_Rusak.setSelected(false);
            nyaman.setKerusakan("rusak");
        }
    }//GEN-LAST:event_RusakActionPerformed

    private void T_RusakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_RusakActionPerformed
        if(T_Rusak.isSelected()){
            Rusak.setSelected(false);
            nyaman.setKerusakan("tidak_rusak");
        }
    }//GEN-LAST:event_T_RusakActionPerformed

    private void AusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AusActionPerformed
        if(Aus.isSelected()){
            T_Aus.setSelected(false);
            nyaman.setKeausan("aus");
        }
    }//GEN-LAST:event_AusActionPerformed

    private void T_AusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_AusActionPerformed
        if(T_Aus.isSelected()){
            Aus.setSelected(false);
            nyaman.setKeausan("tidak_aus");
        }
    }//GEN-LAST:event_T_AusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Kenyamanan_GUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kenyamanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kenyamanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kenyamanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kenyamanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
                new GUI_Kenyamanan().setVisible(true);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Aus;
    private javax.swing.JCheckBox Bau;
    private javax.swing.JCheckBox Bising;
    private javax.swing.JCheckBox Bocor;
    private javax.swing.JButton Menu_Data;
    private javax.swing.JButton Menu_Keamanan;
    private javax.swing.JButton Menu_Kebersihan;
    private javax.swing.JButton Menu_Kenyamanan;
    private javax.swing.JButton Menu_Lingkungan;
    private javax.swing.JCheckBox Rusak;
    private javax.swing.JButton Status_Kelas;
    private javax.swing.JCheckBox T_Aus;
    private javax.swing.JCheckBox T_Bau;
    private javax.swing.JCheckBox T_Bising;
    private javax.swing.JCheckBox T_Bocor;
    private javax.swing.JCheckBox T_Rusak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
