/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventaris;

/**
 *
 * @author kimen
 */
public class GUI_Lingkungan extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Lingkungan
     */
    public GUI_Lingkungan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Status_Kelas = new javax.swing.JButton();
        Menu_Data = new javax.swing.JButton();
        Menu_Kenyamanan = new javax.swing.JButton();
        Menu_Lingkungan = new javax.swing.JButton();
        Menu_Keamanan = new javax.swing.JButton();
        Menu_Kebersihan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Ber_Lantai = new javax.swing.JCheckBox();
        Kot_Lantai = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Ber_Dinding = new javax.swing.JCheckBox();
        Kot_Dinding = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Ber_Atap = new javax.swing.JCheckBox();
        Kot_Atap = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Ber_Pintu = new javax.swing.JCheckBox();
        Kot_Pintu = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Ber_Jendela = new javax.swing.JCheckBox();
        Kot_Jendela = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ANALISA LINGKUNGAN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 430, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Status_Kelas.setText("Inventaris");
        jPanel1.add(Status_Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        Menu_Data.setText("Data Pengguna");
        Menu_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_DataActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        Menu_Kenyamanan.setText("Kenyamanan");
        Menu_Kenyamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KenyamananActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Kenyamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 40));

        Menu_Lingkungan.setText("Lingkungan");
        Menu_Lingkungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LingkunganActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Lingkungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        Menu_Keamanan.setText("Keamanan");
        Menu_Keamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KeamananActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Keamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        Menu_Kebersihan.setText("Kebersihan");
        Menu_Kebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KebersihanActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Kebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -50, -1, 40));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 430));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("1. Kondisi Kebersihan Lantai");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        Ber_Lantai.setText("Bersih");
        Ber_Lantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ber_LantaiActionPerformed(evt);
            }
        });
        jPanel2.add(Ber_Lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Kot_Lantai.setText("Kotor");
        Kot_Lantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kot_LantaiActionPerformed(evt);
            }
        });
        jPanel2.add(Kot_Lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("2. Kondisi Kebersihan Dinding");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        Ber_Dinding.setText("Bersih");
        Ber_Dinding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ber_DindingActionPerformed(evt);
            }
        });
        jPanel2.add(Ber_Dinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Kot_Dinding.setText("Kotor");
        Kot_Dinding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kot_DindingActionPerformed(evt);
            }
        });
        jPanel2.add(Kot_Dinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setText("3. Kondisi Kebersihan Atap");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 20));

        Ber_Atap.setText("Bersih");
        Ber_Atap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ber_AtapActionPerformed(evt);
            }
        });
        jPanel2.add(Ber_Atap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Kot_Atap.setText("Kotor");
        Kot_Atap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kot_AtapActionPerformed(evt);
            }
        });
        jPanel2.add(Kot_Atap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setText("4. Kondisi Kebersihan Pintu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 20));

        Ber_Pintu.setText("Bersih");
        Ber_Pintu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ber_PintuActionPerformed(evt);
            }
        });
        jPanel2.add(Ber_Pintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Kot_Pintu.setText("Kotor");
        Kot_Pintu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kot_PintuActionPerformed(evt);
            }
        });
        jPanel2.add(Kot_Pintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setText("5. Kondisi Kebersihan Jendela");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 20));

        Ber_Jendela.setText("Bersih");
        Ber_Jendela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ber_JendelaActionPerformed(evt);
            }
        });
        jPanel2.add(Ber_Jendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        Kot_Jendela.setText("Kotor");
        Kot_Jendela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kot_JendelaActionPerformed(evt);
            }
        });
        jPanel2.add(Kot_Jendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_DataActionPerformed
        GUI_Data_Kelas gdk = new GUI_Data_Kelas();
        gdk.Data_Kelas();
    }//GEN-LAST:event_Menu_DataActionPerformed

    private void Menu_LingkunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LingkunganActionPerformed
        
    }//GEN-LAST:event_Menu_LingkunganActionPerformed
Analisis lingkung = new Analisis();
    private void Ber_LantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ber_LantaiActionPerformed
        if(Ber_Lantai.isSelected()){
            Kot_Lantai.setSelected(false);
            lingkung.setLantai("bersih");
        }
    }//GEN-LAST:event_Ber_LantaiActionPerformed

    private void Ber_DindingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ber_DindingActionPerformed
        if(Ber_Dinding.isSelected()){
            Kot_Dinding.setSelected(false);
            lingkung.setDinding("bersih");
        }
    }//GEN-LAST:event_Ber_DindingActionPerformed

    private void Ber_AtapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ber_AtapActionPerformed
        if(Ber_Atap.isSelected()){
            Kot_Atap.setSelected(false);
            lingkung.setAtap("bersih");
        }
    }//GEN-LAST:event_Ber_AtapActionPerformed

    private void Ber_PintuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ber_PintuActionPerformed
        if(Ber_Pintu.isSelected()){
            Kot_Pintu.setSelected(false);
            lingkung.setPintu("bersih");
        }
    }//GEN-LAST:event_Ber_PintuActionPerformed

    private void Ber_JendelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ber_JendelaActionPerformed
        if(Ber_Jendela.isSelected()){
            Kot_Jendela.setSelected(false);
            lingkung.setB_jendela("bersih");
        }
    }//GEN-LAST:event_Ber_JendelaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Kot_LantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kot_LantaiActionPerformed
        if(Kot_Lantai.isSelected()){
            Ber_Lantai.setSelected(false);
            lingkung.setLantai("kotor");
        }
    }//GEN-LAST:event_Kot_LantaiActionPerformed

    private void Kot_DindingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kot_DindingActionPerformed
        if(Kot_Dinding.isSelected()){
            Ber_Dinding.setSelected(false);
            lingkung.setDinding("kotor");
        }
    }//GEN-LAST:event_Kot_DindingActionPerformed

    private void Kot_AtapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kot_AtapActionPerformed
        if(Kot_Atap.isSelected()){
            Ber_Atap.setSelected(false);
            lingkung.setAtap("kotor");
        }
    }//GEN-LAST:event_Kot_AtapActionPerformed

    private void Kot_PintuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kot_PintuActionPerformed
        if(Kot_Pintu.isSelected()){
            Ber_Pintu.setSelected(false);
            lingkung.setPintu("kotor");
        }
    }//GEN-LAST:event_Kot_PintuActionPerformed

    private void Kot_JendelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kot_JendelaActionPerformed
       if(Kot_Jendela.isSelected()){
            Ber_Jendela.setSelected(false);
            lingkung.setB_jendela("kotor");
       }
    }//GEN-LAST:event_Kot_JendelaActionPerformed

    private void Menu_KebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KebersihanActionPerformed
        GUI_Kebersihan bersih = new GUI_Kebersihan();
        bersih.Kebersihan_GUI();
    }//GEN-LAST:event_Menu_KebersihanActionPerformed

    private void Menu_KeamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KeamananActionPerformed
        GUI_Keamanan aman = new GUI_Keamanan();
        aman.Keamanan_GUI();
    }//GEN-LAST:event_Menu_KeamananActionPerformed

    private void Menu_KenyamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KenyamananActionPerformed
        GUI_Kenyamanan nyaman = new GUI_Kenyamanan();
        nyaman.Kenyamanan_GUI();
    }//GEN-LAST:event_Menu_KenyamananActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Lingkungan_GUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Lingkungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Lingkungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Lingkungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Lingkungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
                new GUI_Lingkungan().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ber_Atap;
    private javax.swing.JCheckBox Ber_Dinding;
    private javax.swing.JCheckBox Ber_Jendela;
    private javax.swing.JCheckBox Ber_Lantai;
    private javax.swing.JCheckBox Ber_Pintu;
    private javax.swing.JCheckBox Kot_Atap;
    private javax.swing.JCheckBox Kot_Dinding;
    private javax.swing.JCheckBox Kot_Jendela;
    private javax.swing.JCheckBox Kot_Lantai;
    private javax.swing.JCheckBox Kot_Pintu;
    private javax.swing.JButton Menu_Data;
    private javax.swing.JButton Menu_Keamanan;
    private javax.swing.JButton Menu_Kebersihan;
    private javax.swing.JButton Menu_Kenyamanan;
    private javax.swing.JButton Menu_Lingkungan;
    private javax.swing.JButton Status_Kelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
