/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventaris;

/**
 *
 * @author kimen
 */
public class GUI_Kebersihan extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Kebersihan
     */
    public GUI_Kebersihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        Status_Kelas = new javax.swing.JButton();
        Menu_Data = new javax.swing.JButton();
        Menu_Kenyamanan = new javax.swing.JButton();
        Menu_Lingkungan = new javax.swing.JButton();
        Menu_Keamanan = new javax.swing.JButton();
        Menu_Kebersihan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Sir_Lancar = new javax.swing.JCheckBox();
        T_Lancar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        pencahayaan = new javax.swing.JTextField();
        Slider_Pencahayaan = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        Kelembaban = new javax.swing.JTextField();
        Slinder_Kelembaban = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        SuhuRuangan = new javax.swing.JTextField();
        Slinder_Suhu = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Status_Kelas.setText("Inventaris");
        jPanel1.add(Status_Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        Menu_Data.setText("Data Pengguna");
        Menu_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_DataActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        Menu_Kenyamanan.setText("Kenyamanan");
        Menu_Kenyamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KenyamananActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Kenyamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 40));

        Menu_Lingkungan.setText("Lingkungan");
        Menu_Lingkungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LingkunganActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Lingkungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        Menu_Keamanan.setText("Keamanan");
        Menu_Keamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KeamananActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Keamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        Menu_Kebersihan.setText("Kebersihan");
        Menu_Kebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_KebersihanActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Kebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -50, -1, 40));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 430));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATA KEBERSIHAN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 430, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("1. Sirukulas Udara");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Sir_Lancar.setText("Lancar");
        jPanel2.add(Sir_Lancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        T_Lancar.setText("Tidak Lancar");
        T_Lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_LancarActionPerformed(evt);
            }
        });
        jPanel2.add(T_Lancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel3.setText(" 2. Pencahayaan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Slider_Pencahayaan, org.jdesktop.beansbinding.ELProperty.create("${value}"), pencahayaan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(pencahayaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

        Slider_Pencahayaan.setMaximum(350);
        Slider_Pencahayaan.setPaintTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pencahayaan, org.jdesktop.beansbinding.ELProperty.create("${text}"), Slider_Pencahayaan, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        Slider_Pencahayaan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Slider_PencahayaanAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Slider_PencahayaanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(Slider_Pencahayaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, -1));

        jLabel4.setText("3. Kelembaban");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Slinder_Kelembaban, org.jdesktop.beansbinding.ELProperty.create("${value}"), Kelembaban, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        Kelembaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelembabanActionPerformed(evt);
            }
        });
        jPanel2.add(Kelembaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, -1));

        Slinder_Kelembaban.setMaximum(350);
        Slinder_Kelembaban.setPaintTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Kelembaban, org.jdesktop.beansbinding.ELProperty.create("${text}"), Slinder_Kelembaban, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jPanel2.add(Slinder_Kelembaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, -1));

        jLabel5.setText("4. Suhu Ruangan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Slinder_Suhu, org.jdesktop.beansbinding.ELProperty.create("${value}"), SuhuRuangan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(SuhuRuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 60, -1));

        Slinder_Suhu.setMaximum(350);
        Slinder_Suhu.setPaintTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SuhuRuangan, org.jdesktop.beansbinding.ELProperty.create("${text}"), Slinder_Suhu, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jPanel2.add(Slinder_Suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, -1));

        jButton1.setText("Submit");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 430, 320));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_DataActionPerformed
        GUI_Data_Kelas gdk = new GUI_Data_Kelas();
        gdk.Data_Kelas();
    }//GEN-LAST:event_Menu_DataActionPerformed

    private void Menu_LingkunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LingkunganActionPerformed
        GUI_Lingkungan call_lingkung = new GUI_Lingkungan();
        call_lingkung.Lingkungan_GUI();
    }//GEN-LAST:event_Menu_LingkunganActionPerformed

    private void Menu_KebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KebersihanActionPerformed
        
    }//GEN-LAST:event_Menu_KebersihanActionPerformed

    private void Slider_PencahayaanAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Slider_PencahayaanAncestorMoved

    }//GEN-LAST:event_Slider_PencahayaanAncestorMoved

    private void Slider_PencahayaanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Slider_PencahayaanAncestorAdded

    }//GEN-LAST:event_Slider_PencahayaanAncestorAdded

    private void KelembabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelembabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelembabanActionPerformed

    private void T_LancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_LancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_LancarActionPerformed

    private void Menu_KeamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KeamananActionPerformed
       GUI_Keamanan aman = new GUI_Keamanan();
        aman.Keamanan_GUI();
    }//GEN-LAST:event_Menu_KeamananActionPerformed

    private void Menu_KenyamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_KenyamananActionPerformed
         GUI_Kenyamanan nyaman = new GUI_Kenyamanan();
        nyaman.Kenyamanan_GUI();
    }//GEN-LAST:event_Menu_KenyamananActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Kebersihan_GUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kebersihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kebersihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kebersihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kebersihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
                new GUI_Kebersihan().setVisible(true);
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kelembaban;
    private javax.swing.JButton Menu_Data;
    private javax.swing.JButton Menu_Keamanan;
    private javax.swing.JButton Menu_Kebersihan;
    private javax.swing.JButton Menu_Kenyamanan;
    private javax.swing.JButton Menu_Lingkungan;
    private javax.swing.JCheckBox Sir_Lancar;
    private javax.swing.JSlider Slider_Pencahayaan;
    private javax.swing.JSlider Slinder_Kelembaban;
    private javax.swing.JSlider Slinder_Suhu;
    private javax.swing.JButton Status_Kelas;
    private javax.swing.JTextField SuhuRuangan;
    private javax.swing.JCheckBox T_Lancar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField pencahayaan;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
